### ISSUE TITLE
Plugin prompts to save changes even if nothing changed 

### ISSUE THREAD

**Issue by sanoraya** [microsoft/vscode-azurelogicapps#107]
Not end of life of course, but very annoying.

**Comment by joechung-msft** [comment]
Could you elaborate?  When I open a Logic App and then try to close its editor window, it does not prompt me to save changes if I did not make any.

![not-prompted-to-save-changes](https://user-images.githubusercontent.com/26208574/61103721-002b5e00-a428-11e9-824b-42c8094016ef.gif)

**Comment by joechung-msft** [comment]
Perhaps you are talking about when you browse, the editor opens untitled files for the JSON and prompts you to save before letting you close them?

**Comment by sanoraya** [comment]
Yes Joe, you are correct. That's what is happening.

**Comment by joechung-msft** [comment]
Strangely, this only repros in an installed version of the extension and not the development version.  Investigating...

**Comment by DAXaholic** [comment]
I think we could use some helpers from [microsoft/vscode-azuretools](https://github.com/microsoft/vscode-azuretools) like [openReadOnlyJson](https://github.com/microsoft/vscode-azuretools/blob/master/ui/src/openReadOnlyContent.ts#L15) which is also used by [microsoft/vscode-azurefunctions](https://github.com/microsoft/vscode-azurefunctions) to [show](https://github.com/microsoft/vscode-azurefunctions/blob/master/src/commands/viewProperties.ts#L27) the function's properties in a read-only fashion:  

![openReadOnlyJson](https://user-images.githubusercontent.com/5146032/66849248-df1e6000-ef76-11e9-9d14-3a7fa96a004c.gif)


We already have a dependency on a rather old version of it (approx. a year old) which does not contain the mentioned helper method. In the meantime a lot of refactoring took place, e.g. via [Refactor AzureTreeDataProvider](https://github.com/microsoft/vscode-azuretools/commit/ab8883a0d1c944e33a58d139baade9989e13b1af) which means that if we want to leverage it we first have to update to a more recent version.  

At first glance this seems like a non-trivial effort so before potentially jumping into that journey I would like to ask if there are any plans to have the update done by someone from Microsoft. 
If not, is this something the community can/should take care of?

**Comment by joechung-msft** [comment]
I would like to avoid a big refactor if possible, at this time.  I've got a couple big commits coming soon.  In the meantime, perhaps copying `openReadOnlyJson` over by itself and using that would suffice.

**Comment by DAXaholic** [comment]
Ok, makes sense.
I will try to 'cherry-pick' the necessary stuff and integrate it.
Once we moved to a recent version of `microsoft/vscode-azuretools` we can replace it with the 'genuine' implementation.

**Comment by DAXaholic** [comment]
Created the PR, please have a look at it.
I tested it for some of my Logic Apps and could not find any issues.
As this (hopefully) will be a temporary solution I pulled the required functionality into the single file `readOnlyUtils.ts` so that once we move to a more recent version of `microsoft/vscode-azuretools` we just have to remove the file and rewire the four call sites.
