### ISSUE TITLE
Integration Account Config Missing in Exported Template

### ISSUE THREAD

**Issue by derek1ee** [microsoft/vscode-azurelogicapps#120]
When using the Logic Apps Template export functionality in Visual Studio Code, we noticed that the integration account is missing.

The part that is missing is shown below.

"integrationAccount": {
"id": "[concat('/subscriptions/',subscription().subscriptionId,'/resourcegroups/',parameters('ipaasResourceGroupName'),'/providers/Microsoft.Logic/integrationAccounts/',parameters('integrationAccountName'))]"
},

**Comment by joechung-msft** [comment]
It might be better to use the [resourceId](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#resourceid) function instead:
`resourceId('Microsoft.Logic/integrationAccounts', parameters('integrationAccountName'))`

**Comment by joechung-msft** [comment]
Derek, Reid never implemented the "export integration account to template" functionality so this is blocked.
