### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by QamarNomani** [microsoft/vscode-azurelogicapps#137]
- Issue Type: `Performance`
- Extension Name: `vscode-logicapps`
- Extension Version: `0.2.23`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\qamruddinm\ms-azuretools.vscode-logicapps-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by joechung-msft** [comment]
The extension script is bundled.  However, some of our dependencies are not, which can cause the high CPU utilization during script load and processing.

**Comment by joechung-msft** [comment]
In the meantime, what activity were you doing when you experienced the high CPU utilization?

**Comment by joechung-msft** [comment]
Closing due to lack of information.  I'll reopen if we can get a copy of the .cpuprofile.txt mentioned in the initial report.
