### ISSUE TITLE
'recurrence' snippet results in invalid definition

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/vscode-azurelogicapps#138]
just used the 'recurrence' snippet in VScode and hit 'save'. was met with this:
![image](https://user-images.githubusercontent.com/20270743/73281411-d0b22800-41a4-11ea-8610-4bc26e5bed9a.png)

I fixed the issue by manually changing the code to this:
![image](https://user-images.githubusercontent.com/20270743/73281091-4cf83b80-41a4-11ea-9943-f53609481b3f.png)

A better experience would be to have two recurrence snippets: `recurrence-frequency` and `recurrence-scheduled`

**Comment by joechung-msft** [comment]
I'll remove the "schedule" property from the existing recurrence trigger for now.
