### ISSUE TITLE
'Report an Issue' button sends to bad URL

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/vscode-azurelogicapps#139]
Encountered an error while using the Extension and clicked the 'Report an Issue' button that shows up on the Notification:
![image](https://user-images.githubusercontent.com/20270743/73281703-34d4ec00-41a5-11ea-9db8-c2173f8032a3.png)

Upon doing so, a browser opens to a GitHub url that is invalid:
![image](https://user-images.githubusercontent.com/20270743/73281732-40281780-41a5-11ea-9e78-c49528aa8872.png)

seems the button should take users to [the Issues page of this repo](https://github.com/microsoft/vscode-azurelogicapps/issues).

**Comment by joechung-msft** [comment]
This is because of a mismatch between the Github repository name (vscode-azurelogicapps) and the extension name (vscode-logicapps).  I'll investigate if there's a way to remove the "Report an issue" button for now.

**Comment by joechung-msft** [comment]
I might be unable to unblock this by renaming the repository, but I need to OK this with the folks working on v2 (who probably want this repo's name).
