### ISSUE TITLE
Subscription could not be found

### ISSUE THREAD

**Issue by janielMartell** [microsoft/vscode-azurelogicapps#165]
Hello, I'm trying to use the Visual Studio Code extension for Azure Logic Apps but when I try to see the logic apps in my subscription I get an error that says "Error: The subscription 'MY_SUB_ID' could not be found."

I already configured the Azure: Cloud and Azure: Tenant from the Azure Account extension, and my subscription is visible from the Azure: Select Subscriptions. This may or may not be due to my resources existing in a sovereign cloud environment.  Has anyone experienced this?

**Comment by joechung-msft** [comment]
The extension does not support the sovereign clouds yet. #133

**Comment by janielMartell** [comment]
Ah, I figured... It would be nice if it showed a more descriptive error instead. Either way, thanks for clarifying @joechung-msft

**Comment by jimseiwert** [comment]
@joechung-msft do we have any eta for this?

**Comment by joechung-msft** [comment]
There's currently a pull request opened to address this. You can follow its progress in #133.
