### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by onepointWill** [microsoft/vscode-azurelogicapps#178]
Issue Type: <b>Bug</b>

I have installed Azure Logic App from the repository in VSCode. When I use the extension, no Azure subscriptions are shown.

When I look at the console for VSCode I can see that there is an error with a missing module:

"Activating extension 'ms-azuretools.vscode-logicapps' failed: Cannot find module 'vscode-azureextensionui'
Require stack:
- ~/.vscode/extensions/ms-azuretools.vscode-logicapps-0.2.53/out/extension.js"

Running Ubuntu 20.04 

I installed VSCode using Snap

Extension version: 0.2.53
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:56:11.027Z)
OS version: Linux x64 5.4.0-48-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz (4 x 2747)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 1|
|Memory (System)|11.58GB (0.32GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 5f27121a-084d-449a-9ab5-329df6f871a9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by kevinCefalu** [comment]
I can confirm the same.

- Windows 10 v2004 build 19041.508
- VSCode v1.49.3 & v1.50.0-insider
- Installed MS Azure Extensions
    |Name|Version|
    |-|-|
    | ms-azure-devops.azure-pipelines | v1.174.2 |
    | ms-azuretools.vscode-azureappservice | v0.19.0 |
    | ms-azuretools.vscode-azurefunctions | v0.24.1 |
    | ms-azuretools.vscode-azureresourcegroups | v0.2.0 |
    | ms-azuretools.vscode-azurestorage | v0.10.1 |
    | ms-azuretools.vscode-azurevirtualmachines | v0.2.0 |
    | ms-azuretools.vscode-cosmosdb | v0.15.0 |
    | ms-azuretools.vscode-docker | v1.6.0 |
    | ms-azuretools.vscode-logicapps | v0.2.53 |
    | ms-vscode.azure-account | v0.9.3 |
    | ms-vscode.azurecli | v0.5.0 |
    | msazurermtools.azurerm-vscode-tools | v0.12.0 |

> **Note:** Other extensions that make connections to Azure (i.e., ms-azuretools.vscode-azurestorage, ms-azuretools.vscode-azurevirtualmachines) appear to work fine and allow expected functionality.

### Log

``` log
abstractExtensionService.ts:708 Activating extension 'ms-azuretools.vscode-logicapps' failed: Cannot find module 'vscode-azureextensionui'
Require stack:
- c:\Users\Kevin\.vscode-insiders\extensions\ms-azuretools.vscode-logicapps-0.2.53\out\extension.js
- c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code Insiders\resources\app\out\bootstrap-fork.js.
_logMessageInConsole @ abstractExtensionService.ts:707
_logOrShowMessage @ abstractExtensionService.ts:707
$onExtensionActivationError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
```

**Comment by n-irwin** [comment]
Yep Im also having the same

**Comment by joechung-msft** [comment]
`vsce` produced an invalid package when using the `yarn` option. I'll publish a new version using `--no-yarn`.

**Comment by joechung-msft** [comment]
Thanks for reporting this. I just published the hotfix 0.2.54.

**Comment by joechung-msft** [comment]
Possible root cause of issues - https://github.com/microsoft/vscode-vsce/issues/432

**Comment by kevinCefalu** [comment]
Confirmed working after updating to hotfix 0.2.54. Great job, thanks so much!
