### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jberu624** [microsoft/vscode-azurelogicapps#191]
- Issue Type: `Performance`
- Extension Name: `vscode-logicapps`
- Extension Version: `1.0.3`
- OS Version: `Darwin x64 20.2.0`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/nh/1zfdpdmx39391wdr51w09y0c0000gn/T/ms-azuretools.vscode-logicapps-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by joechung-msft** [comment]
I believe this is the same issue as #148. You can share the .cpuprofile.txt with us if you like us to confirm.

The v2 version of the extension avoids this issue by not using the old version of the Azure SDK for Node.js.
