### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nyannios** [microsoft/vscode-azurelogicapps#216]
- Issue Type: `Performance`
- Extension Name: `vscode-logicapps`
- Extension Version: `1.0.16`
- OS Version: `Darwin x64 19.6.0`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/55/t1hrbj5j0n786tt9wv2qchg00000gr/T/ms-azuretools.vscode-logicapps-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nyannios** [comment]
the mcafee virus scanner may be slowing it down too?

**Comment by joechung-msft** [comment]
Can you share the .cpuprofile.txt file you mentioned?
