### ISSUE TITLE
Logic Apps Standard Designer not loading - provider is null

### ISSUE THREAD

**Issue by IainAdamsLabs** [microsoft/vscode-azurelogicapps#218]
Hi,

I am raising this here in hope that somebody from Microsoft takes a look.

https://github.com/Azure/logicapps/issues/334

I am simply trying to get up and running using Logic Apps and am having an issue launching the designer with VSCode. Getting mysterious 'provider is null' error without any further information.

We are both following this tutorial - https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code

Thanks
Iain

**Comment by joechung-msft** [comment]
This repository is for the Consumption extension. I will forward https://github.com/Azure/logicapps/issues/334 to the team for review.
