### ISSUE TITLE
Definition contains invalid parameters.

### ISSUE THREAD

**Issue by klawrawkz** [microsoft/vscode-azurelogicapps#223]
Hi, my name is klawrawkz. I am fine, how are you?

I find this extension to be helpful in conducting many activities in vs code. *Kudos* to you.

By way of a preamble, I don't think this topic is a bug. Rather it is a usability issue. Here's the thing. In some cases it seems that error messages are not very helpful. I don't know if there is a rationale or a technical concern that limits information provided in error messages in vs code.

In a logic app when we view JSON workflows "in the designer" and attempt to save changes, oftentimes we receive an "error" stating that the "definition contains invalid parameters". [Hmmm... What does this mean,](https://user-images.githubusercontent.com/48074223/132764522-91ec6ce1-2842-44f0-8e3a-72c1bd26b91c.png) _"Invalid parameters"_? There is no additional info, and when your workflow is "bigish" attempting to find the offending JSON is like finding a needle in a haystack. [Crap. Why _me?_](https://user-images.githubusercontent.com/48074223/132764872-7dfb519e-2b1c-45a4-b6ba-06c4be2d3ba0.png) Isn't there some way that the offending parameter(s) can be detailed in the error message? If not, how about adding "_logic app JSON validator_" function to this extension?  

Here's the scenario:
1. create a logic app and ensure that it is living in azure
2. open the logic app workflow in vs code
3. in vs code select "open in designer" command
4. designer loads into vs code
5. **_being sure not to make changes_**, click the save icon in vs code "designer" view
6. receive the "Definition contains invalid parameters." error message
7. wonder to self "_how can the definition contain invalid parameters when it is loading from the logic app living in azure_"?

What's the story?

Thanks for the help,

klaw

____________________________
![2021-09-09_16-50-10](https://user-images.githubusercontent.com/48074223/132764522-91ec6ce1-2842-44f0-8e3a-72c1bd26b91c.png)
![2021-09-09_16-57-20](https://user-images.githubusercontent.com/48074223/132764872-7dfb519e-2b1c-45a4-b6ba-06c4be2d3ba0.png)

**Comment by joechung-msft** [comment]
Try asking this at https://github.com/Azure/logicapps/issues. This issues area is for the Consumption version of the extension.

**Comment by klawrawkz** [comment]
ok.

thx.

**Comment by fao001** [comment]
I have the same problem, but i'm using directly from azure portal, and i don't have any idea where the issues is....

**Comment by AshV** [comment]
today my first attempt to explore logic app is ruined coz of this error

**Comment by joechung-msft** [comment]
Please file an issue in https://github.com/Azure/logicapps/issues. This issues area is for the Consumption version of the extension.
