### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by spUK2020** [microsoft/vscode-azurelogicapps#231]
- Issue Type: `Performance`
- Extension Name: `vscode-logicapps`
- Extension Version: `1.0.25`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.62.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\meparkes\AppData\Local\Temp\ms-azuretools.vscode-logicapps-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by joechung-msft** [comment]
Can you share the cpuprofile.txt file indicated in your comment? Thanks.
