### ISSUE TITLE
Error with Logic Apps (Standard) Extension for vscode

### ISSUE THREAD

**Issue by jcetina** [microsoft/vscode-azurelogicapps#236]
I'm using VSCode on Mac OS Big Sur.

Whenever I try to create a logic app project using the aforementioned extension, I get the following error:

`You must have the .NET Core SDK installed to perform this operation. See here for supported versions.`

I've tried using both .NET Core 5 and 6 (uninstalling the other version each time), and it's always the same error. The error comes when I select the type of workflow (Stateful or Stateless) in the `Create New Project `dialogs.

**Comment by joechung-msft** [comment]
Sorry, this is the Issues section for the Consumption extension, not Standard. Try creating the issue in https://github.com/Azure/logicapps/issues instead. Sorry, I could not transfer the issue since it is cross-organization -- Azure → microsoft -- and I do not have permissions.
