### ISSUE TITLE
Cannot get extension to run on M1 Mac

### ISSUE THREAD

**Issue by yobyot** [microsoft/vscode-azurelogicapps#243]
On an M1 Mac, every time I try to create a project with a new Logic App, I receive the following error:

`You must have the [.NET Core SDK](https://aka.ms/AA4ac70) installed to perform this operation. See [here](https://aka.ms/AA1tpij) for supported versions.`

This link takes you to the requirements for the Functions extension, which works fine.

Here's the output of `dotnet --list-sdks` from the `/users/local/share/dotnet/x64` directory:

```
1:47:16 PM callisto /usr/local/share/dotnet/x64> arch
i386
1:47:18 PM callisto /usr/local/share/dotnet/x64> ./dotnet --list-sdks
3.1.417 [/usr/local/share/dotnet/x64/sdk]
5.0.406 [/usr/local/share/dotnet/x64/sdk]
6.0.201 [/usr/local/share/dotnet/x64/sdk]
1:47:27 PM callisto /usr/local/share/dotnet/x64>
```

Here's the output of `dotnet --list-sdks` from `/user/local/share/dotnet' (the ARM directory):
```
1:49:17 PM callisto /usr/local/share/dotnet> arch
arm64
1:49:19 PM callisto /usr/local/share/dotnet> dotnet --list-sdks
6.0.201 [/usr/local/share/dotnet/sdk]
1:49:30 PM callisto /usr/local/share/dotnet>
```

I've tried:
- Opening VS Code in Rosetta
- Altering VS Code's dotnet path settings as follows:
```
    "dotnetAcquisitionExtension.existingDotnetPath": [
    
        {
            "extensionId": "msazurermtools.azurerm-vscode-tools",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "ms-azuretools.vscode-bicep",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "ms-azuretools.vscode-azurefunctions",
            "path": "/usr/local/share/dotnet/x64/dotnet"
        },
        {
            "extensionId": "ms-azuretools.vscode-azurelogicapps",
            "path": "/usr/local/share/dotnet/x64/dotnet"
        },
    ]
```
Note that `ms-azuretools.vscode-azurefunction` _is_ able to find and use the x64 installed SDK and create projects.

Does anyone have any suggestions of what I might have missed or workarounds?

**Comment by joechung-msft** [comment]
Is this for the Standard or Consumption extension? If you're talking about Standard, please visit https://github.com/Azure/logicapps/issues to file an issue.

**Comment by yobyot** [comment]
Thanks, @joechung-msft. Will do.
