### ISSUE TITLE
Cannot select and pick a workflow after upgrading to v1.0.34

### ISSUE THREAD

**Issue by gillesev** [microsoft/vscode-azurelogicapps#261]
Provided you have 2 Logic App (Standard) workflows W1 and W2. We want to invoke workflow W2 from workflow W1.
When upgrading the VSCode Logic App (Standard) extension from 1.0.25 to 1.0.34, we are unable to see the list of workflows to pick from (should show W2) when using the Workflow Invoke action in workflow W1.

**Comment by joechung-msft** [comment]
Please file an issue at [Azure/logicapps](https://github.com/Azure/logicapps/issues) for issues with the Logic Apps (Standard) extension. This repository is for the Logic Apps (Consumption) extension.
