### ISSUE TITLE
Cannot choose my subscription when exporting Consumption workflow to a local project

### ISSUE THREAD

**Issue by ryanpfalz** [microsoft/vscode-azurelogicapps#272]
Background:
I am following the steps outlined in [this guide](https://learn.microsoft.com/en-us/azure/logic-apps/export-from-consumption-to-standard-logic-app#export-consumption-workflows-to-a-local-project).

Setup:
- I have a Consumption Logic App (source) and a Standard Logic App that I am seeking to export the Consumption workflow to. Both resources are in the same Resource Group and are both in the same region (Central US).
- I have Contributor access on the subscription and resource group.
- I have VSCode successfully connected to my Azure subscription via the Azure Account Extension, and I have both the Logic App Standard and Consumption extensions. Both extensions successfully connect to my subscription and I can view/deploy to the Logic Apps mentioned above.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/19982322/220975459-2f90bea2-6dae-4c88-817c-e53f12acdca6.png">

<img width="218" alt="image" src="https://user-images.githubusercontent.com/19982322/220976155-57a442d3-95d0-4905-91d2-00de9efa9b4e.png">

- I am running .NET SDK 6.0.406 and Functions Core Tools 4.0.4736

Issue/Reproduction Steps:
When I choose 'Export Logic App' in the Logic App Standard extension, my subscription does not appear in the 'Select a subscription' dropdown, so I cannot proceed with the export process.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/19982322/220976691-4ebe2ab0-aabe-44a5-80ed-a3a612d7e496.png">

Expected Outcome:
My subscription should appear in the 'Select a subscription' dropdown, just like as is [shown in the documentation](https://learn.microsoft.com/en-us/azure/logic-apps/export-from-consumption-to-standard-logic-app#select-logic-apps-for-export).

**Comment by joechung-msft** [comment]
Please file issues with the Logic Apps (Standard) extension at https://github.com/Azure/logicapps/issues
