### ISSUE TITLE
Quickstart / Getting Started Doc Needed

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/vscode-azurelogicapps#32]
After you install it in VS Code, how do you create a new Logic App? Is there a quickstart doc?

**Comment by nzthiago** [comment]
I see the "Create and manage automated logic app workflows - Visual Studio Code"
https://docs.microsoft.com/en-us/azure/logic-apps/create-logic-apps-visual-studio-code

**Comment by ecfan** [comment]
@nzthiago If we had a more beginner-friendly experience, we'd promote this article into the quickstart section. :)

**Comment by nzthiago** [comment]
I was confused seeing the "Create" quickstarts for Portal and Visual Studio at the top, and not the VS Code one. To me it'd make sense still under quickstart, with a caveat at the top of the article saying something along the lines of the VS Code experience is entirely JOSN centric and to go to the Portal or Visual Studio if they need the full visual creation experience...

**Comment by ecfan** [comment]
@nzthiago Copy, will do, thanks!

**Comment by ecfan** [comment]
The new URL will be: https://docs.microsoft.com/azure/logic-apps/quickstart-create-logic-apps-with-visual-studio
