### ISSUE TITLE
Autocomplete seems incorrect

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/vscode-azurelogicapps#36]
After creating a new Logic App, I went to the `triggers` property, and did Ctrl+<space> in it.

I would have expected to get an option for all the triggers I could use at that point. However I'm met with this:
![image](https://user-images.githubusercontent.com/20270743/46558673-c169e580-c8a2-11e8-96bc-26d1dfa65ebe.png)

Which doesn't seem valid. Now, if I **know** what I want here, I can start typing the name of the trigger, say "Recurrence", and I'll get something useful:
![image](https://user-images.githubusercontent.com/20270743/46558698-dba3c380-c8a2-11e8-907c-279776fc72a2.png)

But I would have expected that in a dropdown of Ctrl+<space> at that point.

**Comment by brandonh-msft** [comment]
Piggybacking on this; trying to fill out headers for a response action. I'm not sure what the format is, and there doesn't seem to be any intellisense here to help me out. Are we expecting an array of json key/value objects? an array of colon-separated strings? not sure.

**Comment by joechung-msft** [comment]
There are no suggestions here, because you have to name the operation first, e.g., "Every_day" below:
````
{
  "triggers": {
    "Every_day": {
      "type": "Recurrence",
      "inputs": {
        "frequency": "Hour",
        "interval": 1
      }
    }
  }
}
````

**Comment by brandonh-msft** [comment]
#46 is a more descriptive version of this
