### ISSUE TITLE
There is no source control on the json of the Logic App. 

### ISSUE THREAD

**Issue by paloukari** [microsoft/vscode-azurelogicapps#38]
There is no collaboration feature in the tool, similar to source control, where two devs can edit the same logic app concurrently. There is no way to know that the json I will submit from VS Code is the latest version of the file.

**Comment by joechung-msft** [comment]
There is a version history available, but it is a limitation that we do not offer source control.

**Comment by joechung-msft** [comment]
We recently implemented local projects which allow you to save Logic App deployment templates locally.  You can use source control to manage these and even set up an Azure DevOps pipeline to build and deploy these automatically on repository update.
