### ISSUE TITLE
Wrong subscription icon

### ISSUE THREAD

**Issue by jongio** [Microsoft/vscode-azurelogicapps#40]
The icon that looks like a filter here:
![image](https://user-images.githubusercontent.com/2163001/46559302-d182c480-c8a4-11e8-80ce-dc5c11cfbf41.png)

Should be a key, like in the azure portal:
![image](https://user-images.githubusercontent.com/2163001/46559317-de071d00-c8a4-11e8-8eb5-07be2ddae378.png)

**Comment by joechung-msft** [comment]
This is by design.  The button lets you filter which subscriptions you would like to see in the tree view.

**Comment by jongio** [comment]
Right. But I’m this context the filter icon next to the header Logic Apps isn’t clear that you are filtering subscriptions. It looks like you are filtering Logic Apps.

**Comment by joechung-msft** [comment]
We are filtering Logic Apps by subscription.
