### ISSUE TITLE
When/how is the LA updated in to Azure?

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/vscode-azurelogicapps#41]
I've got a Logic App created, but I'm not sure if it's been updating in Azure with each save, or do I need to do an additional step?

I'm not seeing a "publish" option when I right click the file in the workspace either at the tab level
![image](https://user-images.githubusercontent.com/20270743/46559611-b9f80b80-c8a5-11e8-9f7b-b6a652c9e6ca.png)

 or the explorer (left-side) level
![image](https://user-images.githubusercontent.com/20270743/46559632-c2504680-c8a5-11e8-88fe-f497f1a4b6a0.png)

**Comment by joechung-msft** [comment]
When you save a Logic App, it should prompt you with a dialog to update the definition in your subscription.

![image](https://user-images.githubusercontent.com/26208574/46636104-a221c100-cb0b-11e8-9cc8-f22d306602da.png)

If you clicked "Always upload," it won't prompt you any more and will upload on each save.  If you want to reset that setting to prompt you again, you can change this setting:

![image](https://user-images.githubusercontent.com/26208574/46636132-bc5b9f00-cb0b-11e8-991c-7ed437e6fd5f.png)

**Comment by brandonh-msft** [comment]
I started seeing this after my first LA, but hadn't seen it prior to that. 🤷‍♂️
