### ISSUE TITLE
The setting for 'upload always' is shared with Integration Accounts preference

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/vscode-azurelogicapps#44]
Currently if you click on "Upload Always" but then want to change that setting back, you'll only see it under the Integration Accounts preferences and not Logic Apps which can be confusing:
<img width="860" alt="screen shot 2018-10-05 at 1 59 06 pm" src="https://user-images.githubusercontent.com/1563288/46560051-24f61200-c8a7-11e8-9345-6208ec569504.png">

**Comment by joechung-msft** [comment]
I am unable to reproduce this issue:

![image](https://user-images.githubusercontent.com/26208574/46636208-09d80c00-cb0c-11e8-94cd-f2a24dfcd027.png)

Can you open your settings.json (... menu) and share that?

**Comment by nzthiago** [comment]
Hi Joe - I just typed "Logic" again in the search and this time it shows back the separate settings for Logic Apps and for Integration Accounts; not really sure why it only showed Integration Accounts before, I wonder if it was in an in-between state and the setting hadn't been set yet for Logic Apps:
![image](https://user-images.githubusercontent.com/1563288/46677048-a810b400-cb96-11e8-8013-88c74da47b0c.png)
