### ISSUE TITLE
Feature request: compare two versions

### ISSUE THREAD

**Issue by nzthiago** [microsoft/vscode-azurelogicapps#45]
Clicking on versions for a Logic Apps gives you the JSON for that previous version of the Logic Apps. Would be great to be able to compare two versions:
<img width="289" alt="screen shot 2018-10-05 at 2 15 52 pm" src="https://user-images.githubusercontent.com/1563288/46560604-3b04d200-c8a9-11e8-9f24-e6eb66a6d75e.png">

**Comment by joechung-msft** [comment]
Closing all the enhancement requests. v2 is the future of Logic Apps on Visual Studio Code.
