### ISSUE TITLE
No intellisense on the parameters object 

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/vscode-azurelogicapps#47]
If I wanted to define a parameter for my Logic App, the JSON schema provides no assistance in how one is structured. It'd be great to have a `parameter` snippet I can fire off & then fill out for my parameter

**Comment by joechung-msft** [comment]
You must name the parameter first before being offered suggestions:
![image](https://user-images.githubusercontent.com/26208574/46635429-40605780-cb09-11e8-9853-b9e1a58bd4bf.png)

**Comment by brandonh-msft** [comment]
of course, but having a `parameter` snippet here (like we do for triggers) would let me know what you're looking for within the `parameters` group
