### ISSUE TITLE
[Feature Request]: Infer JSON Schema from example w/in the editor

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/vscode-azurelogicapps#49]
When adding a trigger like 'Request' or an action like Parse JSON or HTTP, it's useful to have that JSON Schema defined. However, I don't know many people that can create a JSON schema off the top of their head ;)
That said, could we have similar functionality _within VSCode_ that can infer the JSON schema given a example JSON object? Would be very beneficial to present that functionality when a user is sitting inside one of the `schema` properties for applicable triggers/actions.

**Comment by joechung-msft** [comment]
This is a limitation of Visual Studio Code's JSON Schema support:  https://github.com/Microsoft/vscode/issues/45207

**Comment by brandonh-msft** [comment]
hmm. reading the linked bug it doesn't seem to address my suggestion; I want to be able to have a way to paste my JSON sample in to the editor, and it to spit out a schema for me to use in this LA action (like i can in the designer)

**Comment by joechung-msft** [comment]
If they resolve that bug, you can add a "$schema" property to your JSON schema, and it'll automatically use the JSON schema for JSON schema to validate your JSON schema, something like:
````
{
  "type": "Request",
  "kind": "Http",
  "inputs": {
    "schema": {
      "$schema": "http://json-schema.org/draft-04/schema#
    }
  }
}
````

**Comment by brandonh-msft** [comment]
right, that feature is all I'm requesting here. In the designer, you paste a sample, it generates the schema, and puts it inline in the json definition (for stuff like HTTP Body). That's would be a start.

What I *think* you're talking about is the ability to, after this schema's been inferred & inlined, use it to reference pieces of the associated payload later on in the logic app (like the designer provides). That, in my opinion, is a nice-to-have but not what I was looking for w/ this particular issue.

**Comment by joechung-msft** [comment]
Closing all the enhancement requests. v2 is the future of Logic Apps on Visual Studio Code.
