### ISSUE TITLE
'triggers' is plural. Does that mean we can have more than one?

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/vscode-azurelogicapps#50]
I noticed while working in the JSON that `triggers` was plural. Made me wonder if I can have two of them. The schema, turns out, **does** allow you to do this. It even deployed out to Azure.
However, upon viewing the Logic App in Azure, designer view refused to load and kicked me back out to code view (no errors or complaints, though).

If in fact multiple triggers are a thing, it'd be good to see some examples & docs around when/why one might take this approach.

**Comment by joechung-msft** [comment]
It is a limitation of the Logic Apps designer that it does not allow more than one trigger.  However, the Logic Apps runtime supports more than one trigger.

**Comment by brandonh-msft** [comment]
sweet; would be cool to see some docs/samples on this

**Comment by joechung-msft** [comment]
The extension supports multiple triggers so closing this.  I've asked PMs about documenting this though be advised that support for multiple triggers is being considered for deprecation.
