### ISSUE TITLE
For a 'Request' trigger you can't see the generated URL to call the Logic App

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/vscode-azurelogicapps#51]
How do I get the URL for an http 'Request' trigger?
<img width="1270" alt="screen shot 2018-10-05 at 2 50 25 pm" src="https://user-images.githubusercontent.com/1563288/46561802-0fd0b180-c8ae-11e8-90b9-37e6deb63ff8.png">

**Comment by joechung-msft** [comment]
It is a separate API call to get the callback URL for a trigger.  This would be a good feature to add though, perhaps as a context menu item on the trigger.

**Comment by joechung-msft** [comment]
You can now see the callback URL in the read-only designer we just added.
