### ISSUE TITLE
[Feature request]: Live update the designer view when I edit the workflow

### ISSUE THREAD

**Issue by fiksen99** [microsoft/vscode-azurelogicapps#99]
Ideally, I'd be able to see my changes locally in the designer view so that I can edit my workflow locally, and explore the changes that I've made to ensure they're doing what I expect, before submitting it to azure.

Currently I have to save my changes to azure, then reload the designer to see the changes in a workflow format.

**Comment by joechung-msft** [comment]
Closing all the enhancement requests. v2 is the future of Logic Apps on Visual Studio Code.
